name: Build fatjar on push to master
on:
  push:
    branches:
      - main
jobs:
  gradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: 'zulu'
          cache: 'gradle'
      - name: Execute Gradle shadowJar
        run: ./gradlew shadowJar
      - uses: actions/upload-artifact@v3
        with:
          name: Package
          path: build/libs/modification-updater.jar
